# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'OMODFramework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  name: nexusKey
  inputs:
    secureFile: 'nexus_api_key'

- task: CmdLine@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    script: |
      echo Copying $(nexusKey.secureFilePath) to the Release test folder
      
      mkdir OMODFramework.Test\bin\Release\
      
      move $(nexusKey.secureFilePath) OMODFramework.Test\bin\Release\nexus_api_key.txt

- task: VSTest@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testFiltercriteria: 'TestCategory!=OMODExtraction'

- task: CopyFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/OMODFramework/bin/$(buildConfiguration)/netstandard2.0/'
    Contents: |
      OMODFramework.deps.json
      OMODFramework.dll
      OMODFramework.pdb
    TargetFolder: '$(Build.ArtifactStagingDirectory)/OMODFramework'

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/OMODFramework'
    ArtifactName: 'OMODFramework'
    publishLocation: 'Container'

- task: CopyFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/OMODFramework.Scripting/bin/$(buildConfiguration)/'
    Contents: |
      OMODFramework.Scripting.dll
      OMODFramework.Scripting.pdb
    TargetFolder: '$(Build.ArtifactStagingDirectory)/OMODFramework.Scripting/'

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/OMODFramework.Scripting/'
    ArtifactName: 'OMODFramework.Scripting'
    publishLocation: 'Container'

- task: NuGetCommand@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'pack'
    packagesToPack: '**/OMODFramework.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)/NuGet/OMODFramework'
    versioningScheme: 'off'
    includeSymbols: true

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/NuGet/OMODFramework'
    ArtifactName: 'OMODFramework.NuGet'
    publishLocation: 'Container'

- task: NuGetCommand@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'pack'
    packagesToPack: '**/OMODFramework.Scripting.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)/NuGet/OMODFramework.Scripting/'
    versioningScheme: 'off'
    includeSymbols: true

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/NuGet/OMODFramework.Scripting/'
    ArtifactName: 'OMODFramework.Scripting.NuGet'
    publishLocation: 'Container'