# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'OMODFramework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  name: nexusKey
  inputs:
    secureFile: 'nexus_api_key'

- task: CmdLine@2
  inputs:
    script: |
      echo Copying $(nexusKey.secureFilePath) to the debug test folder
      
      mkdir OMODFramework.Test\bin\Debug\
      
      move $(nexusKey.secureFilePath) OMODFramework.Test\bin\Debug\nexus_api_key.txt

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
